---
#For more details, visit https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: npm run dev
    env: 
      DATABASE_URL: postgres://gitpod@localhost/journalEntries
  - command: npx prisma studio
    env: 
      DATABASE_URL: postgres://gitpod@localhost/journalEntries

ports: 
  - port: 5173
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
  - port: 5555
    onOpen: open-browser


vscode:
  extensions:
    - svelte.svelte-vscode
    - Prisma.prisma


github:
  prebuilds:
    master: true
    branches: true 
    pullRequests: true
